version: '3.9'
services:

  #Configurações Webserver
  webserver:
    image: webdevops/php-dev:8.0-alpine
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PHP_DEBUGGER: "xdebug"
      XDEBUG_START_WITH_REQUEST: 1
      XDEBUG_DISCOVER_CLIENT_HOST: 1
      XDEBUG_CLIENT_HOST: "10.254.254.254"
      XDEBUG_CLIENT_PORT: 9000
      XDEBUG_IDE_KEY: PHPSTORM
      PHP_IDE_CONFIG: "serverName=localhost"